### ISSUE TITLE
Slow to open (+45 seconds)

### ISSUE THREAD

**Issue by dfishburn** [jreybert/vimagit#65] opened 2016-02-02 14:27 UTC
I am running on Windows, when executing shell commands with Vim, there is a little popup that shows up in the Windows taskbar.  So if I run :grep or other such commands, this "cmd.exe" task will be present until the task completes.

When I open :Magit
I can see that cmd.exe window flashing over and over and over.

I would like to know a couple of things.
1. What commands are actually being executed (is there any logging I can enable in Magit)?
2. Why is it executing so many commands (I assume it is walking the directory tree and executing a command for every sub directory).
3.  I also assume #2 is actually running diff commands as well?

The reason I ask, is when I hit R (for refresh) in the Magit window this just took 45 seconds.  Which is an absolute AGE.  Yet, if I run :git status, I get essentially the same information in 1 second (minus the diffs).

Depending on your answer, here are some in advance.

If it is the diffs that are taking Magit so long to open, is it possible to turn those off by default and just show the modified files (just like git status).  Then having a mapping which I use to ask Magit to fetch the diffs for the file (quite often these diffs are useful).  If this could allow me to run :Magit in 2 seconds v 45 seconds it would make me user experience much much better.

David

**Comment by fpnick** [comment] 2016-02-02 14:35
For me it also takes quite long under Linux, at least with our main (fairly big) repository.
This is sad, but I guess it's due to Vimagit's early development stage. Let's hope it gets better, soon ;)

**Comment by jreybert** [comment] 2016-02-02 19:58
Hi @dfishburn 

> is there any logging I can enable in Magit

yes, you can enable a profiling function:
`:call magit#utils#start_profile("path_to_profile_output")`

> is it possible to turn those off by default and just show the modified files

yes, you can try to set:
`:let g:magit_default_show_all_files=0`

Again, it is difficult to me to enhance experience with windows, as I don't work with such environment. Someday, I will install a virtual machine with Windows, when I'll find some time :)

Hi @fpnick , thanks for your report. There is an existing bug report about performance issues with Linux. If you mind, you may want to update it: #36. But you are right, performance is important, but reliability is more important IMO (I guess you don't want me to play evil with your git repo :smiling_imp: ). And if reproduce bug is dificult, reproduce performance issue is even harder!

**Comment by dfishburn** [comment] 2016-02-02 20:38
Thanks,

```
let g:magit_default_show_all_files=0
```

This changed the load time from 45 seconds to 4-7 seconds.
Once I have some changes to merge I will be able to validate what it is doing.

I will also give the logging a try and see where I get.

Thanks for the reply.
David

**Comment by jreybert** [comment] 2016-02-02 21:18
Woot, 10x speed up :clap:

Still, if you're OK to go deeper in analysis, I would need some git status output, see if play with lot of modified files, big changes in files, submodules and so on.

Anyway, thanks for your time.

**Comment by dfishburn** [comment] 2016-02-04 19:17
BTW, my time with 45 seconds down to 4-5 seconds, seems to be related to how many buffers I have open in Vim.

Since I restarted Vim, things are much faster and I have probably 10 files open instead of 100.  Not sure if Magit is doing anything different / buffer?  Can you let me know if I need to pursue that.

I tried the profiling:

```
:call magit#utils#start_profile("path_to_profile_output")
```

With an appropriate filename ("C:\temp\magit_profile1.txt").
And did the following:

```
Started Vim
:Magit
:bw!
:call magit#utils#start_profile("C:\temp\magit_profile1.txt")
:Magit
:q
```

Then tried to find that file.  It was never written.  According to :h :profile, the profile file should have been written when Vim was closed.  Not sure why it wasn't written, but will pursue that again when I have more time.

Right now I am running with 39 buffers open (many are temporary from other plugins).
:Magit - 8 seconds
Refresh - 5 seconds

I of course still see it shelling out and running lots of commands.

**Comment by jreybert** [comment] 2016-02-08 08:54
> Since I restarted Vim, things are much faster and I have probably 10 files open instead of 100. Not sure if Magit is doing anything different / buffer? Can you let me know if I need to pursue that.

I don't see why a lot of opened files would slow down vimagit. There may be a weird side effect, but I don't have any lead about this.

> Then tried to find that file. It was never written.

Yes, it should be written when you exit vim. Did you searched if there is a special behavior with windows?

> I of course still see it shelling out and running lots of commands.

For each file present in `git status` output, I check if this file is:
- a symlink
- a submodule
- a directory
- an empty file
- a binary file (should be fixed soon in windows)
- or a regular modified file

Each entry may be visible or not (default behavior is set with `g:magit_default_show_all_files`): if an entry is visible, vimagit also get the diff content (`git diff` output for modified file, list of files for new directories, diff summary for modified submodule).

Most of these output need external commands. I did not know the behavior of "shelling out" on Windows. It could be interesting to find a comparison of typical execution overhead on Windows and Linux.

**Comment by jreybert** [comment] 2016-11-02 11:57
Hi, what is the status with current master/next branch?

**Comment by jreybert** [comment] 2017-02-23 21:19
I close this ticket as I can't reproduce the issue. Feel free to reopen it if you encounter the same problem.

**Closed as completed by jreybert** 2017-02-23 21:19 UTC
Labels: help wanted, feedback
