### ISSUE TITLE
[neovim] nvim hangs on git repo with submodules

### ISSUE THREAD

**Issue by zimski** [jreybert/vimagit#45] opened 2015-11-20 16:56 UTC
When i fire up `vimagit` on a `git repo` with several submodules. it hangs and consume 100% of one cpu core.

The hang in noticed only on `neovim`

the traditional `vim` take some seconds. but no hangs noticed.

```
Version used:
Vim: 7.4   2013
Neovim: 0.0.0-alpha compiled oct 9 2015
```

**Comment by jreybert** [comment] 2015-11-20 17:35
Could you post the output of git submodule status please? And also git status.

**Comment by zimski** [comment] 2015-11-20 17:46
```
git status
==========

On branch master
Your branch is up-to-date with 'origin/master'.
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

    modified:   .gitmodules
    new file:   bundle/vim-javascript

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

    modified:   .vimrc
    deleted:    bundle/indent/html.vim
    deleted:    bundle/indent/javascript.vim
    modified:   bundle/vim-javascript (new commits)
    modified:   bundle/vimgit (new commits)
    modified:   sessions/chef.vim
    modified:   sessions/engine.vim
    modified:   sessions/fstrz.vim
    modified:   sessions/vim.vim

Untracked files:
  (use "git add <file>..." to include in what will be committed)

    bundle/vim-javascript-syntax/
    init.vim
    sessions/tests.vim
    spell/

```

```
submodule status
================

-baf5b6cf9decafd1b4dac13ec535e4803b1318d2 bundle/AutoCWD
 f3bdefba787d3748d09d4db520403b627abac0c6 bundle/CamelCaseMotion (heads/master)
 b294c6680e2e114f8b480ce9fec55738c9bee6fd bundle/ag (0.26.0-8-gb294c66)
 d3a00f8affb091e7a14eb34f1beb9db9bb57a4bf bundle/ag_vim (d3a00f8)
 f3fbe427f7b4ec436416a5816d714dc917dc530b bundle/argtextobj (1.1.1)
 7fb632aab475b1d2560fe18a329742ba3b4725c6 bundle/commentary (v1.2-10-g7fb632a)
 b5d3fe66a58a13d2ff8b6391f4387608496a030f bundle/ctrlp.vim (1.79-27-gb5d3fe6)
 937d61ba545ca6719a9305c0c361314a100ad0e9 bundle/ferret (0.3-22-g937d61b)
 3b98a7fcae8f9fff356907171f0406ff8cd28921 bundle/nerdtree (4.2.0-198-g3b98a7f)
 832efc23111d19591d495dc72286de2fb0b09345 bundle/replaceWithRegister (1.42)
 710a854f6a6832004b225c25d5c076bb537fd589 bundle/syntastic (3.6.0-68-g710a854)
 71ec1cbe8f9ead9805f8e0c3b76c590aeb5ed0b7 bundle/tslime.vim (heads/master)
 13ee9f456ac1a7d9e427874c7a6981c2461a6c4d bundle/vim-airline (v0.7-5-g13ee9f4)
 73e3e717be98433a56fe6fe169b40c797a6f8a3f bundle/vim-ctrlp-tjump (0.2.0)
 9ceebf91fc137644cf0693561a386ef4071dbf87 bundle/vim-easymotion (v2.1.0-1-g9ceebf9)
 34719016ec934609387e90804ad49b3d221f0b19 bundle/vim-fugitive (v2.2)
 e5efbaffc066ababc9ae0d689c7050fa5d6591bd bundle/vim-gitgutter (remotes/origin/stage-201-33-ge5efbaf)
 185e609717181b1729984272b34f577aa1f047ff bundle/vim-jade (185e609)
-1d8c2677d26d6b3950b90dc1636e63334c8efc3b bundle/vim-javascript
 3e6b8fb6f03f13434543ce1f5d24f6a5d3f34f0b bundle/vim-misc (1.17.6)
 a0d39b8da5e5835746ad00936e4bcb3a11dfaf42 bundle/vim-rooter (heads/master)
 a74cf38c6031b51d803123bce2cd83902708b56d bundle/vim-rspec (remotes/origin/refactor-plugin-7-ga74cf38)
 397d6378431eb6a9caa56991591e88a3d5d53f68 bundle/vim-session (2.13)
 fa433e0b7330753688f715f3be5d10dc480f20e5 bundle/vim-surround (v2.0-8-gfa433e0)
 57b289fda5be654891a968298fde174e0c4e33c7 bundle/vim-tmux-navigator (v1.0~5)
+8f8bea6d8a540048b5dca728c54c3b2bb8377b06 bundle/vimgit (1.4.1-26-g8f8bea6)
 4151af0d071503fa7f728dc7779370059258a0e9 fonts (heads/master)

```

**Comment by jreybert** [comment] 2015-11-20 21:18
Hm, I can't reproduce. I can see you have new, modified and uninitialized submodules. I tried to reproduce such behavior, but I don't see any stall.

I am using neovim too. You did not mention the precise version of neovim you are using. Don't you have any sha1 or something more precise in :version?

Then, could you profile the stalling execution:

<pre>
:call magit#utils#start_profile("/tmp/log")
:Magit
:qa
</pre>

Thanks a lot, you seems to be a real bug magnet :)

**Comment by zimski** [comment] 2015-11-20 22:03
I upgrated `neovim` to the last version from the `ubuntu depo`

```
NVIM 0.1.0-dev (compiled Nov 18 2015 15:07:14)
```

I succeed to stop the hang by pressing multiple times `ctrl + c`

The profile file is pretty big, but this  data caught my attention ( you will find the complete profiles at the end of this post)

```
FUNCTIONS SORTED ON SELF TIME
count  total (s)   self (s)  function
    1              0.107980  magit#git#submodule_status()
    1   0.009837   0.009669  magit#git#set_top_dir()
    1   0.008087   0.007911  magit#git#is_work_tree()
    2   0.076567   0.000616  magit#git#get_status()
    6   0.040121   0.000197  magit#git#git_diff()
    1   0.000110   0.000108  magit#sign#find_signs()
   12              0.000087  magit#git#top_dir()
    1              0.000026  magit#sign#init()
    1   0.000150   0.000025  magit#sign#remove_all()
    1   0.000015   0.000013  magit#sign#remove_signs()
                             magit#git#git_sub_summary()
                             magit#git#git_dir()
                             magit#sign#add_sign()
                             magit#git#git_apply()
                             magit#git#git_unapply()
                             <SNR>121_get_next_sign_id()
                             magit#git#git_add()
                             magit#git#git_checkout()
                             magit#sign#find_stage_signs()
                             magit#sign#toggle_signs()
```

I can't understand why the `magit#git#top_dir` is called 12 times. i run only one time `:Magit`
I found any function that hang and consume a lot of times

The profile for Neovim http://pastebin.com/qt30Mahs
The profile for Vim http://pastebin.com/GeQPVvGY

Glad to help ;)

**Comment by jreybert** [comment] 2015-11-20 22:46
Grumf, the faulty function profiling has not been dumped...

So, we need drastic measures!
- start neovim in safe mode: `nvim -u /dev/null`
- add vimagit path in runtime path: `:set runtimepath+=/path/to/vimagit/`
- source vimagit plugin: `:source /path/to/vimagit/plugin/magit.vim`
- `:15verbose call magit#show_magit('v')`
- press Space until you stall

We should get the backtrace of the stalling function.

FYI, top_dir() is called before calling some git functions, functions which need to be called from top_dir(). Basically, vimagit perform a :lcd top_dir() before these git functions.

**Comment by jreybert** [comment] 2015-11-20 23:01
BTW, what is your git version?

**Comment by jreybert** [comment] 2015-11-20 23:08
Ouch, I checked a second time your git status. What the hell are you doing with vim-javascript submodule?

The submodule seems to be new,added,modified and also maybe deleted in the same time Oô

Could you report:
- git diff --staged .gitmodules
- git submodule --staged summary
- git submodule summary

If the fault comes from here, thanks, I would never have written such corner case test :D

**Comment by jreybert** [comment] 2015-11-24 11:59
hi zimski, do you have any update about this bug?

**Comment by zimski** [comment] 2015-11-24 12:07
Hi Jerome,
Sorry, i get a lot of works to do this days, i will try to find some free times during this week to investigate this issue.

Have a good day ;)

**Comment by jreybert** [comment] 2015-11-24 12:09
Thanks!

**Comment by jreybert** [comment] 2016-01-05 10:57
Hi zimski,

do you still have freeze with submodules?

If not, could you please close the issue?

**Comment by jreybert** [comment] 2016-04-15 12:30
As I can't reproduce you issue, I close this ticket. Feel free to reopen it if you have any new input about this issue.

**Closed as completed by jreybert** 2016-04-15 12:30 UTC
Labels: bug, help wanted
